AUTH_MS_BASE_URL = "http://localhost:8000"
ORDERS_MS_BASE_URL = "http://localhost:8001"
PRODUCTS_MS_BASE_URL = "http://localhost:8002"
TENANT_MS_BASE_URL = "http://localhost:8003"
WISHLIST_MS_BASE_URL = "http://localhost:8004"
